### PR TITLE
Various Q-Chem Updates

### PR DESCRIPTION
**Pull request by samblau**
## Summary

* Totally overhauled frequency flattening optimization
* Refined error handlers
* Many more tests added

### CODE REVIEW

**Comment by samblau** [comment]
May I ask why we're using Travis instead of Circle here? Our use of conda in Circle allows for very easy open babel installation. I'll try and get babel working with our Travis configuration, but last time I tried, installing babel without conda was a major pain.

**Comment by shyuep** [comment]
I am happy to use conda for travis if you manage to figure out how to get travis to work with conda.

**Comment by samblau** [comment]
Why use travis at all when Circle works so well?

**Comment by samblau** [comment]
Success! Travis is now using Conda. @shyuep would you like me to turn on pycodestyle for custodian like you've done for pymatgen?

**Comment by shyuep** [comment]
Thanks. No need to turn on pycodestyle for now. I haven’t cleaned up custodian yet. Will merge now

**Pull request merged**
