### PR TITLE
Qchem updates: improved handling of scratch files and scratch directories

### PR DESCRIPTION
**Pull request by samblau**
## Summary

Resolves previous problems with scratch directories and saving scratch files. Now explicitly sets both QCSCRATCH and QCLOCALSCR correctly and employs a better procedure for saving scratch files of interest. Also standardizes scratch directory naming and placement to avoid unnecessary confusion.

### CODE REVIEW

**Comment by samblau** [comment]
@shyuep I'm confused why the CI tests aren't getting run? Please advise. Thanks!

**Comment by samblau** [comment]
@shyuep Sorry to pester you, but any progress on this? I'm eager for the tests to start running so that I can fix any small issues and we can get this merged in. Thanks!

**Comment by shyuep** [comment]
I have no idea why your CI tests are not run. Can you pull in all the latest master branch with your repo? I believe this should trigger the tests.

**Comment by samblau** [comment]
Hi @shyuep, my qchem branch is already up to date with the master branch - it is 17 commits ahead and zero commits behind master. So when I attempt to pull Custodian master into my qchem branch, there's nothing for me to push, and thus no way to trigger the tests. Perhaps I'm missing something? Thanks!

**Comment by samblau** [comment]
@shyuep I pushed a commit with a tiny change to a comment in order to trigger the tests. CircleCI did trigger, but it immediately failed with a permissions problem. Please advise. Thanks!

**Comment by shyuep** [comment]
@samblau I just updated the master branch to remove CircleCI testing and add pymatgen style Github action testing. Right now, the tests are failing mainly because of QChem code. Pls merge with main master again and just make sure that the qchem code pass the testing workflow and we will be good to merge.

**Comment by shyuep** [comment]
@samblau Just to let you know that I have pushed a bunch of linting fixes to all the classes. Pls merge the master again. All remaining problems should just be within the qchem package. So once you have those fixed, we can merge.

**Comment by samblau** [comment]
@shyuep Thanks, working on it. Unfortunately, the fact that our new testing environment doesn't use Conda means that I have no viable way to install openbabel (pip install openbabel has been broken basically forever), and the most important part of my Custodian code checks a key from QCOutput which is generated with openbabel functionality. If I go the Pymatgen route of skipping tests that require openbabel if it isn't installed, then most of my tests will be skipped. I guess I'll have to just ignore checking that output key if it isn't present, but it's not ideal. I definitely preferred the previous testing environment based on Conda, but life goes on.

**Comment by shyuep** [comment]
@samblau Can you mock the openbabel output? That is usually the way I would handle this problem. In general, the unit tests are not meant to test that something like openbabel gives the correct output, but rather that given a certain output, what is the action meant to be taken. E.g., we do not run VASP in our tests for VaspJob.

**Comment by samblau** [comment]
@shyuep Yeah, I similarly am not running QChem for QCJob tests, I just copy over the output files that would have been generated. But QCJob.opt_with_frequency_flattener parses an output file via Pymatgen's QCOutput, and QCOutput checks for structure changes that may have occurred during an optimization by constructing molecule graphs for the initial and final structures and seeing if they're isomorphic, and molecule graphs are build by deducing bonding with the OpenBabelNN() local env strategy. So there's no straightforward way to mock that functionality. 

The options I see are to either make the check of opt_outdata["structure_change"] only happen in QCJob.opt_with_frequency_flattener if the "structure_change" key is present in opt_outdata, or to have QCOutput automatically populate that "structure_change" key with the value "no_change" if Openbabel isn't present. I'm leaning towards the former.

**Comment by shyuep** [comment]
Well, I am not familiar with the entire thing. So you can just go ahead and implement whichever one you see fit. The general idea is to test as much of the code that is not openbabel related as possible. Frankly, openbabel is really un-userfriendly in terms of installation. We can consider using conda for Github actions if it is really needed.

**Comment by shyuep** [comment]
@samblau I just figure out how to enable openbabel. For the ubuntu-based workflows, we can simply use sudo apt-get to install it. I just added this to the testing workflow. You can merge and try your tests again.

**Comment by samblau** [comment]
@shyuep Ahhh very nice, thank you! I tried using apt to install it, but had a permissions problem and didn't think I could sudo. I did find another way of doing it but just hadn't yet gotten the chance to putting it into practice. I'll keep ironing this out right now.

**Comment by samblau** [comment]
@shyuep sudo apt-get ended up still not fixing the problem for some reason, but I got the conda install of openbabel working instead and both 3.7 and 3.8 Testing now passes. Will work on resolving the Linting errors now.

**Comment by samblau** [comment]
@shyuep All tests passing! Would it be possible for you to please merge and then release a new version? That way I can get going on the complementary Atomate PR right away. Thanks so much!

**Comment by shyuep** [comment]
Done!

**Pull request merged**
