### PR TITLE
alternative strategy to avoid BRMIX error

### PR DESCRIPTION
**Pull request by tschaume**
Our current VASP installation (v5.2) used for MP production was compiled using the Intel compiler. Apparently, this causes some of our static GGA calculations to throw a serious BRMIX error, which results in custodian to reach its maximum allowed errors. After quite some trial and error, the following strategy using a combination of generation style, kpoints and ISYM settings seems to allow many of our failed static GGA runs to complete successfully.

For instance, starting with the default settings of

```
Monkhorst   —   [12, 12, 12]   —   ISYM default
```

the static GGA run throws a BRMIX error and custodian aborts it after a certain step - as expected. Normally, custodian would now react by setting ISYM to 0, changing to the Gamma generation style, and removing the CHGCAR/WAVECAR files. This will cause the job to restart another 4 times until it hits the maximum number of errors allowed and then fizzle. However, I can get the run to complete successfully on the second try, by instead keeping the CHGCAR/WAVECAR files and the ISYM default, switching to Gamma generation style, and increasing the kpoints by one to make it odd:

```
keep CHGCAR and WAVECAR
Gamma       —   [13, 13, 13]   —   ISYM default
```

The only caveat is the warning

```
random wavefunctions but no delay for mixing, default for NELMDL
```

where `initial charge from wave function` should show up in the VASP output.

This pull request is a preliminary implementation of this strategy. It’s obviously conflicting with what custodian would normally do in this situation. @shyuep, what would be a good way to implement multiple different recipes to be tried for the same error - in this case, the above strategy before switching to ISYM = 0 (which apparently runs significantly slower)?

Note that this implementation is currently being used in MP's production but does not necessarily need to be part of the official custodian. I'm fine with simply keeping this pull request and the respective branch for record and discussion purposes only.

### CODE REVIEW

**Comment by shyuep** [comment]
I would say that the strategy should just account for the number of errors that have occurred. If the BRMIX has occurred more than once, then the new strategy would be used. This can be done by introducing a state variable, e.g., self.error_count["brmix"] = 1, 2, ....

**Comment by tschaume** [comment]
Ok, thanks. I added a commit in which custodian employs different strategies based on a counter for BRMIX errors. It's been successfully tested with a few static GGA runs in MP production. If the current solution is OK, I can also fix the unit test if you plan to merge this pull request.

**Comment by shyuep** [comment]
Looks good. Go ahead.

**Comment by tschaume** [comment]
The unit test for the BRMIX error handler is fixed. I included a more meaningful test to assure that the number of kpoints is odd after calling `h.correct()`.

**Comment by shyuep** [comment]
Thanks for the quick response!

**Pull request merged**
