### PR TITLE
Fix openbabel install to ensure q-chem tests run

### LINKED ISSUE #319: 🚨 Q-Chem tests are not running in CI 🚨
### Problem

The Q-Chem tests are all being skipped in `main`! Tagging @espottesmith and @samblau.

### Proposed Solution

TBD.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by Andrew-S-Rosen**
Closes #319.

@espottesmith and @samblau: I could use your help to resolve the test errors that have come about over the 7+ months since the q-chem tests have been silently being skipped.

### CODE REVIEW

**Comment by espottesmith** [comment]
Yeah, I can help here if you need.

**Comment by Andrew-S-Rosen** [comment]
@espottesmith --- thank you! I'll give you write access. Help needed 😅

**Comment by espottesmith** [comment]
Alright. Will try to get to this over the next couple of days. As you can imagine, I won't be writing many PRs next week.

**Comment by Andrew-S-Rosen** [comment]
@janosh or @shyuep: could we get this merged so the Q-Chem tests run again? Looks like they weren't running for 7+ months...

Thanks @samblau for fixing this up!!

**Review by janosh — COMMENTED** [review]
thanks everyone for catching and fixing this!

**Pull request merged**
