### PR TITLE
[VASP] Adjust SCF Ladder for meta-GGAs/hybrids

### LINKED ISSUE #178: [VASP] NonConvergingErrorHandler for meta-GGAs/hybrids
Currently, the SCF algorithm ladder in `NonConvergingErrorHandler` is tuned for GGAs and is not appropriate for meta-GGAs or hybrids. For instance, meta-GGAs should rarely be used with Algo = VeryFast or Fast (Algo = All is generally recommended and is the default in `MPScanRelaxSet`). For hybrids, Algo = Fast or VeryFast should never be used according to the VASP manual, as hybrids don't support these algorithms even though no warning is printed: https://www.vasp.at/wiki/index.php/LHFCALC.

Will be closed when #179 is merged.

### PR DESCRIPTION
**Pull request by arosen93**
Closes #178.

- This PR addresses the fact that VeryFast --> Fast --> Normal --> All should not be the default scheme for meta-GGAs/hybrids.

- If a meta-GGA functional is used, go straight to Algo = All if it wasn't already set. Algo = All is recommended in the VASP manual (https://www.vasp.at/wiki/index.php/METAGGA) and some of the meta-GGAs (e.g. the Minnesota functionals) explicitly say to set Algo = All for proper convergence. The `MPScanRelaxSet` already uses Algo = All as the default, but other users may not be so careful.

- If a hybrid functional is used, do not set Algo = Fast or VeryFast. Hybrid calculations do not support these algorithms even though no warning is printed (https://www.vasp.at/wiki/index.php/LHFCALC). Instead, do Algo = All if it's not already set. `MPHSERelaxSet` already uses Algo = All. In principle, if Algo = All doesn't work, one could switch to Algo = Damped with TIME = 0.5 per the VASP manual, but given the high cost of hybrids, I do not know that this is advisable in general and so I have left it as a comment.

From the VASP manual:
>It is recommended to select a "direct optimization" algorithm for HF/DFT hybrid functonal type calculations, i.e., ALGO=Damped (IALGO=53) or ALGO=All (IALGO=58) in the INCAR file. The blocked-Davidson algorithm ALGO=Normal is, with certain caveat, also supported, whereas calculations for the other algorithms (ALGO=Fast) are not properly supported (note: no warning is printed). The blocked-Davidson algorithm (ALGO=Normal) is generally rather slow, and in many cases the Pulay mixer will be unable to determine the proper ground-state.

### CODE REVIEW

**Comment by rkingsbury** [comment]
Thanks @arosen93 ! In this and in your other PRs, I'd advocate that you include the rationale from your first post as comments to the code, for the benefit of future devs. You should also add unit tests for revised handlers; I can help you with that if you have questions.

**Comment by arosen93** [comment]
Thanks for the comments, @rkingsbury! I'll add the code comments right now, and I'm meeting with @mkhorton tomorrow to discuss how to best handle the unit tests. Hopefully then I can make these PRs a bit more robust.

**Comment by arosen93** [comment]
Okay, this one should be done now too.

**Comment by arosen93** [comment]
@shyuep, the PRs (#179, #180, #182, #183, #184) I have opened are now complete. They should pass all tests, and I don't have anything to add. Please let me know if there are any additional changes that you would like to see in order for them to be merged. Thanks!

**Pull request merged**
