### PR TITLE
Handle new symmetry precision error

### PR DESCRIPTION
**Pull request by mkhorton**
Needs a test file.

### CODE REVIEW

**Comment by mkhorton** [comment]
Tests pass locally, this should be ready to merge. I'm not sure why CI is not working on the PR but seems like an unrelated issue.

To summarize changes, this introduces a handler for a new warning in VASP6, "symprec noise". 

To recover, it first attempts to lower SYMPREC, and if this still fails, it turns symmetry off altogether.

**Comment by rkingsbury** [comment]
@mkhorton I think if you pull the latest upstream master the CI tests should run. If you can do that, perhaps we can roll this PR into a release along with #161 and #162 ?

**Comment by mkhorton** [comment]
Thanks @rkingsbury; @shyuep CI runs here now and tests pass, can this be merged?

We're planning on using this in production since it fixes an important new warning we see in VASP6.

**Comment by shyuep** [comment]
@rkingsbury @mkhorton Release done.

**Comment by mkhorton** [comment]
Thanks!

**Pull request merged**
