### PR TITLE
VASP Handler: Remove deprecated handlers and kwargs

### PR DESCRIPTION
**Pull request by arosen93**
This PR removes handlers that have aged past their deprecation time. There is no attached issue.

### CODE REVIEW

**Comment by arosen93** [comment]
@shyuep this is ready to merge.

**Comment by mkhorton** [comment]
Removing a keyword argument (`natoms_large_cell`) causes issues with already-serialized Custodian objects, e.g. attached to workflows, especially since the `VaspErrorHandler` doesn't accept arbitrary keyword arguments.

**Comment by mkhorton** [comment]
i.e., this PR is a breaking change. I'm not sure the best resolution, but I imagine it will cause issues for any existing users of custodian with large databases that encode the specific error handlers they use, leading to de-serialization errors or an inability to upgrade custodian (a minimal fix could just be to add `**kwargs` to `VaspErrorHandler.__init__` as a no-op).

**Comment by arosen93** [comment]
Good point. Alright, I can just as easily put it back! Easy enough. I'll open a PR.

**Comment by mkhorton** [comment]
It’s not the most elegant solution, but maybe just the `**kwargs` addition is sufficient, rather than adding it all back: this way we still remove the old, deprecated code, but do not encounter de-serialisation issues.

**Pull request merged**
