### PR TITLE
error handling the single frequency cases for two atoms [WIP]

### PR DESCRIPTION
**Pull request by rdguha1995**
## Summary

Handles the QChem Parsing error when we have fragments with single frequencies

It is a WIP. I have arbitrarily assigned the second frequency to a very large value. Needs review

Problem :- When running FFOpt with fragments with two atoms there is a single frequency but the parser looks for a second frequency and throws up an error-  `freq_1 = freq_outdata.get(\"frequencies\")[1]\nIndexError: index 1 is out of bounds for axis 0 with size 1\n" `

Proposed Solution :- Check the length of freq_outdata.get(''frequencies") and arbitrarily assign a high positive value to freq_1 if length of freq_outdata.get(''frequencies") is 1.

Added a test: OptFF_single_freq_frags in test_jobs.py
Should be reviewed by @samblau before merge

### CODE REVIEW

**Comment by samblau** [comment]
@shyuep Could you please approve the running of the test workflows? Thanks!

**Comment by samblau** [comment]
@shyuep circling back on this, could you please approve the running of the test workflows? thanks!

**Comment by mkhorton** [comment]
Hi @samblau @rdguha1995 I approved the running of CI for this PR since I have permissions to do so. However, I am not a maintainer of this repo so cannot merge or release.

**Comment by shyuep** [comment]
thanks.

**Pull request merged**
