### PR TITLE
QChem Refactor and Update

### PR DESCRIPTION
**Pull request by samblau**
* QChem functionalities have been refactored to be named consistently with other packages
* SCF and geometry optimization error handling substantially improved
* Tests have been udpated and supplemented accordingly

### CODE REVIEW

**Comment by samblau** [comment]
Sorry about that. Just changed it back. If you don't mind doing a new release of pymatgen now, I can fix the requirements to reference the latest release and the deal with the last couple of testing issues

**Comment by samblau** [comment]
Speaking of those issues though - once again the problems are entirely due to babel-based tests that I need to skip in a creative way. However, I know that it is possible to get conda correctly installed with circle-ci such that all tests can be run, as they are with atomate. I assume I could do something similar for travis-ci. Is this something you would be open to? Or should I just keep skipping tests that need babel? Thanks!

**Comment by samblau** [comment]
If possible, would greatly appreciate a new pymatgen release and your thoughts on the babel tests tonight or tomorrow morning so that we can get this merged in and I can open the atomate pull request tomorrow afternoon. Thanks, Shyue!

**Comment by samblau** [comment]
All QChem tests now pass, including those that require OpenBabel! 

Unfortunately, in the process, two vasp tests are now failing that weren't before. I'm guessing the root cause is the installation of python-dev that I needed to do in travis.yml in order to get OpenBabel to install properly, but I can't say for sure. I also am hesitant to try and fix them given that I know very little about the vasp side of things. 

Furthermore, in the python 2.7 build only, two syntax errors in pymatgen's io/babel.py are raised. I'm wondering if these were not caught at the pymatgen level because all Babel-based tests have been skipped. I'm going to go and try and get Babel working with pymatgen and see if other issues arise. They could also just be 2.7 problems which aren't found in pymatgen because it only tests with python 3.6. Perhaps it's time to only test custodian with 3.6 as well such that it is consistent with pymatgen and atomate?

**Comment by samblau** [comment]
And yes, I know I'm still doing a bad thing here referencing the pymatgen repo rather than the latest release. I can switch that back once you're ready to release the latest pymatgen, but I wanted to leave it "wrong" in this pull request for the moment so that you can see the various testing successes / failures

**Comment by shyuep** [comment]
I don't have an objection to rmeoving py27, but why are there hard coded paths in the qchem/jobs.py file? That cannot be how this software is designed.

**Comment by samblau** [comment]
Are you referring to /dev/shm/qcscratch/? I believe we have talked about this briefly before, but that is just directing QChem to scratch directly to shared memory and is general on any linux machine.

**Comment by shyuep** [comment]
Yes, but that's just for Linux. Is it general to all OSes?

**Comment by samblau** [comment]
I will research it more. However, that path was not added or changed by this pull request. Perhaps we could get this merged in so that the refactor can be finished consistently and I can get atomate updated too, and then you can open an issue about this path specifically so that we can work on fixing separately?

**Comment by samblau** [comment]
And by "get this merged in", I mean release a new pymatgen version so that I can fix the requirements, and then this pull request can be merged

**Comment by shyuep** [comment]
Pls fix failing tests before I merge.

**Comment by samblau** [comment]
Collaborator accidentally merged changes directly into my repo and broke the tests. I rolled that commit back so they all work again. However, the requirements are still bad at present - they point to the master pymatgen repo because I still need a release to point to instead that includes my recent refactor pull request. If you could please release a new version of pymatgen, I can fix the requirements here and then this should be good to merge. Thanks!

**Comment by samblau** [comment]
Ready to merge!

**Comment by shyuep** [comment]
There are failing tests. Pls fix.

**Comment by samblau** [comment]
I'm confused - did the tests start to fail due to changes made after the request was merged? Because here I'm not seeing any failing tests. Should I start another pull request having only incorporated your last few commits since the merge and debug from there? Please advise. Thanks!

**Comment by shyuep** [comment]
Go to circle CI and look at the tests on the official custodian branch. There are failing tests due to missing keys in qchem. It is definitely not related to other parts of custodian

**Comment by samblau** [comment]
Ah, I understand. Immediately after the merge you added CircleCI to the test suite. I will investigate the issues revealed by circle first thing tomorrow morning.

**Pull request merged**
