### PR TITLE
Q-Chem 6 + Misc Updates

### PR DESCRIPTION
**Pull request by samblau**
## Summary

* Major changes to Q-Chem error handlers given new functionality and defaults associated with recently released version 6 of the code

### CODE REVIEW

**Comment by rkingsbury** [comment]
Thanks @samblau ! Looks good to me (for what it's worth). I like the very descriptive new `print` statements for the unhandled errors.

**Comment by samblau** [comment]
@shyuep I'm seeing a lot of VASP tests fail. None of my Q-Chem tests are failing. I believe this might be due to me updating to the latest version of pymatgen? Any thoughts? Thank you!

**Comment by samblau** [comment]
Hey @shyuep, following up here - any thoughts on what's going on? There are people waiting for my full Q-Chem 6 infrastructure to be merged into all three master repos, and I've been waiting on Atomate until this is merged, but I really don't know what's going on since all of my code here is working. Your assistance would be greatly appreciated.

**Comment by samblau** [comment]
@rkingsbury Any thoughts on what's going on with the VASP handlers here? Thanks!

**Comment by rkingsbury** [comment]
> @rkingsbury Any thoughts on what's going on with the VASP handlers here? Thanks!

Not sure; I can't see it being related to anything you've done in this PR. All the test failures seems to result from

`pymatgen.core.structure.StructureError: The list of atomic species must be of the same length as the list of fractional coordinates.`

Maybe there was a change in `Structure` in the latest pymatgen version that hasn't been picked up by custodian yet?

**Comment by JaGeo** [comment]
We also made some changes in the lobster part in pymatgen. We can also offer to check our implementations here again. I assume at least one of the failures comes from this. (Cc @naik-aakash )

**Comment by naik-aakash** [comment]
Ahh , I see. Thanks @JaGeo for pointing this out. Will fix the Lobster-related test issues. Somehow I missed updating it. Will raise a PR and fix it sometime

**Comment by JaGeo** [comment]
Pinging @janosh here as well as he might know more about the structure-related updates.

**Comment by janosh** [comment]
> Pinging @janosh here as well as he might know more about the structure-related updates.

I'm not aware of any breaking changes in `pymatgen/core/structure.py`. Just looked through that file's recent history but nothing stood out as potentially causing downstream errors. If a change like that _did_ slip in, happy to help revert it asap.

Do the tests here pass again if reverting the `pymatgen` version in `requirements-ci.txt` back to `pymatgen==2022.5.26`?

Either way, if all the tests covering code in this PR pass, we could merge it anyway if it's time sensitive.

**Comment by shyuep** [comment]
@samblau I am not sure what is happening, but the tests wqith the QCHEM changes take > 3 hrs to run. For reference, the version without the QChem updates took 3 mins to run. Is there a reason why this would be the case?

**Comment by shyuep** [comment]
I am going to revert this change as I need to do a release already.

**Comment by janosh** [comment]
You can make a release from any past commit without reverting.

**Comment by janosh** [comment]
See e.g. the [`test.yml`](https://github.com/materialsproject/pymatgen/actions/workflows/test.yml) workflow in pymatgen that's setup so you can do this through the web UI:

Screenshot 2023-03-08 at 11 51 29

**Comment by shyuep** [comment]
@janosh I know. But the main branch should be clean. I will revert and a new PR can be submitted when all these issues are fixed.

**Comment by samblau** [comment]
@shyuep I have no idea why the Q-Chem tests are taking that long. Directly running the three Q-Chem tests on my local machine (test_jobs.py, test_handlers.py, test_job_handler_interaction.py) takes 20 seconds, 18 seconds, and 16 seconds respectively.

**Comment by samblau** [comment]
@shyuep are you sure that the Q-Chem tests are the ones actually taking all of that time?

**Comment by shyuep** [comment]
@samblau You are right. When I run the tests on my local machine, everything works fine. I am not sure what is happening witht he CI.

**Pull request merged**
