### PR TITLE
VASP Handler: Add a new correction for the ZPOTRF ZTRTRI error that is specific to small structures

### LINKED ISSUE #213: VASP error: ZPOTRF ZTRTRI can be due to too high NCORE or NPAR
The below VASP error can also happen if NCORE or NPAR is set to an unusually large value. I got the below error when accidentally setting NCORE = 64 for a 1-atom job. We might want to add logic for that at some point.

```
 -----------------------------------------------------------------------------
|                                                                             |
|     EEEEEEE  RRRRRR   RRRRRR   OOOOOOO  RRRRRR      ###     ###     ###     |
|     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
|     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
|     EEEEE    RRRRRR   RRRRRR   O     O  RRRRRR       #       #       #      |
|     E        R   R    R   R    O     O  R   R                               |
|     E        R    R   R    R   O     O  R    R      ###     ###     ###     |
|     EEEEEEE  R     R  R     R  OOOOOOO  R     R     ###     ###     ###     |
|                                                                             |
|     Orbital orthonormalization failed in the inversion of matrix            |
|     scaLAPACK: Routine ZPOTRF ZTRTRI failed! kpoint: 7 spin: 1              |
|                                                                             |
|     Possible solutions for this issue are:                                  |
|     - Please check whether the atoms are too close to each other.           |
|     - Decreasing POTIM might help during relaxations or MDs.                |
|     - Deleting CHGCAR or WAVECAR if incompatible with the structure.        |
|     - Try calculating without symmetrizing (ISYM = 0 or ISYM = -1).         |
|     - As last resort: using a different PAW for some of the atoms.          |
|                                                                             |
|       ---->  I REFUSE TO CONTINUE WITH THIS SICK JOB ... BYE!!! <----       |
|                                                                             |
 -----------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by arosen93**
Closes #213. A new handler for ZPOTRF ZTRTRI in VASP is made for small structures. This will likely cause a trivial merge conflict with #249, but I'll fix it when the time comes.

### CODE REVIEW

**Comment by arosen93** [comment]
@shyuep --- this one is ready to merge.

**Comment by shyuep** [comment]
There seems to be merge conflicts introduced from merging the other PRs. While I can theoretically fix this on my end, I think it might be better for you to do it to make sure it is correct done. 

Thanks for all the contributions!

**Comment by arosen93** [comment]
@shyuep --- This one is ready to go now too. Thanks!

**Comment by arosen93** [comment]
@shyuep --- looks like my last-second merge conflict fix didn't, well, fix. I'll submit a new PR to fix the master branch.

**Pull request merged**
