### PR TITLE
Better convergence handling - VASP

### PR DESCRIPTION
**Pull request by shyamd**
Suggested method for laddering from VeryFast to All iteratively if electronic convergence is not met in VASP:
Solves this feature request - #75 
- Removes changes in mixing params
- Moves from VeryFast to Fast to Normal to All

### CODE REVIEW

**Comment by shyamd** [comment]
So the handlers have different mixing parameter logic based on whether its the UnconvergedErrorHandler or NonConvergingErrorhandler:

I have no clue for which one to use since even the VASP manual is pretty vague about this.

**Comment by computron** [comment]
The logic you've implemented in this PR (ladder down the Algo, then change mixing parameters only after hitting ALGO=All rather than up front) is in-line with what I would do based on my qualitative experience. But it is not really justified by real data. Up to @shyuep whether he wants to merge I guess, but I personally don't have any issues with it.

**Comment by shyamd** [comment]
@shyuep,
Any chance you're going to accept this? Anecdotally, I've had a number of weird structures, particularly HOIP substitutions converge using Algo  = All under regular GGA+U that didn't with fast or normal, and Algo = ALL was slower than the other two per SCF, so I believe this laddering is, in fact, a speed/stability trade-off.

**Comment by shyuep** [comment]
I need to see data on the tradeoffs. I cannot make a decision based on this alone. I would say that if HOIP requires different treatment, by all means have a different VASP handler for them. 

I am confused by what you mean by GGA+U for HOIP. As far as I know, there are no U elements in HOIP, unless you are referring to the literature proposed value of U=8eV for Pb (which frankly sounds ridiculous to me).

**Comment by computron** [comment]
Any update on this PR? Curious whether it will be part of main custodian

**Comment by shyuep** [comment]
My previous comment still stands.

**Comment by shyamd** [comment]
Here's the results of a structured test on perturbed silicon supercell. I repeated this 4 times to get an average for the LOOP times and number of LOOP itterations for SCF.

- 432 Atom super cell (6x6x6)
- All positions pertubed by 0.05 A
- Static calculation to stress test the SCF convergence
- Max SC Steps set to 200
- VASP 5.4.4 with MPRelaxSet 
- 1 Cori Haswell Node, 24 total MPI tasks
- Max memory is total for all 24 tasks measured by SLURM


|           | GGA                     |              |                 | SCAN                    |              |                 |
|-----------|-------------------------|--------------|-----------------|-------------------------|--------------|-----------------|
| Algorithm | Average  LOOP Time  (s) | Num SC steps | Max Memory (GB) | Average  LOOP Time  (s) | Num SC steps | Max Memory (GB) |
| Very Fast | 72                      | 34           | 19              | 497                     | Failed       | 43              |
| Fast      | 120                     | 31           | 19              | 493                     | Failed       | 43              |
| Normal    | 168                     | 25           | 19              | 496                     | 104          | 43              |
| All       | 192                     | 22           | 23              | 776                     | 68           | 58              |

**Pull request merged**
