### PR TITLE
Address new VASP6 inconsistent Bravais lattice error

### PR DESCRIPTION
**Pull request by arosen93**
In VASP6, there appears to be a new error which I have included below:
```
-----------------------------------------------------------------------------
|                                                                             |
|     EEEEEEE  RRRRRR   RRRRRR   OOOOOOO  RRRRRR      ###     ###     ###     |
|     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
|     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
|     EEEEE    RRRRRR   RRRRRR   O     O  RRRRRR       #       #       #      |
|     E        R   R    R   R    O     O  R   R                               |
|     E        R    R   R    R   O     O  R    R      ###     ###     ###     |
|     EEEEEEE  R     R  R     R  OOOOOOO  R     R     ###     ###     ###     |
|                                                                             |
|     Inconsistent Bravais lattice types found for crystalline and            |
|     reciprocal lattice:                                                     |
|                                                                             |
|        Crystalline: base-centered monoclinic                                |
|        Reciprocal : triclinic                                               |
|                    (instead of base-centered monoclinic)                    |
|                                                                             |
|     In most cases this is due to inaccuracies in the specification of       |
|     the crytalline lattice vectors.                                         |
|                                                                             |
|     Suggested SOLUTIONS:                                                    |
|      ) Refine the lattice parameters of your structure,                     |
|      ) and/or try changing SYMPREC.                                         |
|                                                                             |
|       ---->  I REFUSE TO CONTINUE WITH THIS SICK JOB ... BYE!!! <----       |
|                                                                             |
 -----------------------------------------------------------------------------
```
It appears to occur when SYMPREC is very low. I have confirmed that increasing SYMPREC resolves the issue, as suggested by VASP. 

I have now addressed this error in Custodian and added test files.

### CODE REVIEW

**Comment by janosh** [comment]
I also encountered this error several times. @arosen93 Thanks for fixing!

**Comment by mkhorton** [comment]
@shyuep, would it be possible to review some of @arosen93's PRs for merging? There are several important updates for best practices and VASP 6. I can vouch for Andrew's VASP knowledge.

**Comment by shyuep** [comment]
Merged and new version just released. Thanks all!

**Comment by mkhorton** [comment]
Thanks!

**Comment by arosen93** [comment]
Thank you!!

**Pull request merged**
